[package]
name = "vostok"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.27.2"
egui = "0.27.2"
env_logger = "0.11.3"
log = "0.4.21"
rand = "0.8.5"
rustls = "0.23.7"
unic = "0.9.0"
url = "2.5.0"
